apiVersion: ea/v1
kind: System
metadata:
  id: marketplace-inventory
  repo: marketplace-aigen/inventory
spec:
  owner: team-mp-inventory
  domain: inventory
  pnl: marketplace
  stack: java-msfw
  fitnessFunctions:
    domainIsPure: enforce
    useCaseSliceIsolation: enforce
    aggregateEncapsulation: enforce
    entityEncapsulation: enforce
    stateWritersPublish: enforce
  waivers: []
